version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tailwind_apache2
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tailwind_phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root

  db:
    image: mysql:8.0
    container_name: tailwind_mysql_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tailwind
      - MYSQL_USER=tailwind
      - MYSQL_PASSWORD=tailwind
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
